# Generated by Django 3.2.12 on 2022-03-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0003_alter_emailpin_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpin',
            name='status',
            field=models.CharField(blank=True, choices=[('activated', 'Activated'), ('notactivated', 'Not Activated')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='emailpin',
            name='pin_code',
            field=models.CharField(help_text='encrypted pin code', max_length=2048),
        ),
    ]
