# Generated by Django 3.2.12 on 2022-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0004_auto_20220318_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpin',
            name='status',
            field=models.CharField(blank=True, choices=[('activated', 'Activated'), ('notactivated', 'Not Activated')], default='notactivated', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
