# Generated by Django 3.2.12 on 2022-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0006_authredirect_domaingroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('otp_key', models.CharField(max_length=2048, unique=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=100, null=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
