# Generated by Django 3.2.12 on 2022-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0010_auto_20220822_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domaingroup',
            old_name='enabled_allowed_users',
            new_name='enable_allowed_users',
        ),
    ]
