# Generated by Django 3.2.12 on 2022-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0012_domaingroup_lookup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaingroup',
            name='allowed_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
