# Generated by Django 3.2.12 on 2022-08-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0013_alter_domaingroup_allowed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainGroupAuthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(blank=True, choices=[('otp', 'OTP'), ('emailpin', 'Email PIN')], default='none', max_length=100, null=True, verbose_name='Login Method')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssoapp.domaingroup')),
            ],
        ),
    ]
