# Generated by Django 3.2.12 on 2022-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0014_domaingroupauthtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaingroup',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
