# Generated by Django 3.2.12 on 2022-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0016_auto_20220831_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='authredirect',
            name='session_auth_url',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
