# Generated by Django 3.2.12 on 2022-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0017_authredirect_session_auth_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authredirect',
            name='session_auth_url',
        ),
        migrations.AddField(
            model_name='domaingroup',
            name='session_auth_url',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
